
import React, { useState, useEffect, useRef } from 'react';
import { Project, ProjectFile } from '../types';
import { 
  FileCode, Plus, Monitor, 
  Smartphone, Tablet, RefreshCw, Sparkles, Send,
  Image as ImageIcon, ChevronDown, Settings, X,
  FolderOpen, Trash2, FileJson, FileType, Wand2, Menu,
  MessageSquare, User, Bot, Terminal, Zap
} from 'lucide-react';
import { applyAgenticEdit } from '../services/geminiService';

interface Props {
  project: Project;
  files: ProjectFile[];
  onFilesUpdate: (files: ProjectFile[]) => void;
}

const getFileIcon = (fileName: string, language: string) => {
    if (language === 'image') return <ImageIcon size={14} className="mr-2 text-purple-400" />;
    if (fileName.endsWith('.json')) return <FileJson size={14} className="mr-2 text-yellow-400" />;
    if (fileName.endsWith('.css')) return <FileType size={14} className="mr-2 text-blue-400" />;
    if (fileName.endsWith('.js')) return <FileCode size={14} className="mr-2 text-yellow-300" />;
    if (fileName.endsWith('.html')) return <FileCode size={14} className="mr-2 text-orange-400" />;
    return <FileCode size={14} className="mr-2 text-slate-400" />;
};

export const Ide: React.FC<Props> = ({ project, files, onFilesUpdate }) => {
  const [activeFile, setActiveFile] = useState<string>('index.html');
  const [isSidebarOpen, setIsSidebarOpen] = useState(true);
  
  // AI Agent State
  const [chatHistory, setChatHistory] = useState<{role: 'user'|'ai', text: string}[]>([]);
  const [agentInput, setAgentInput] = useState('');
  const [isThinking, setIsThinking] = useState(false);
  const chatEndRef = useRef<HTMLDivElement>(null);

  // Initialize Standard Files to save AI Tokens
  useEffect(() => {
    // If we only have the core AI files (index/css/js), let's add some "Virtual" files
    // to make the IDE look professional without wasting AI tokens generating them.
    const standardFiles = [
        { name: 'package.json', content: `{\n  "name": "${project.config.idea.toLowerCase().replace(/[^a-z0-9]/g, '-').substring(0, 20)}",\n  "version": "1.0.0",\n  "type": "module"\n}`, language: 'json' },
        { name: 'README.md', content: `# ${project.name}\n\nGenerated by NexusBuild AI.`, language: 'markdown' }
    ];

    const missingFiles = standardFiles.filter(sf => !files.some(f => f.name === sf.name));
    if (missingFiles.length > 0) {
        onFilesUpdate([...files, ...missingFiles as any]);
    }
  }, []);

  useEffect(() => {
      chatEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [chatHistory, isThinking]);

  const handleCodeChange = (newContent: string) => {
    const updatedFiles = files.map(f => f.name === activeFile ? { ...f, content: newContent } : f);
    onFilesUpdate(updatedFiles);
  };

  const handleAgentSubmit = async () => {
    if (!agentInput.trim()) return;
    setIsThinking(true);
    setChatHistory(prev => [...prev, { role: 'user', text: agentInput }]);
    
    // Optimistic UI
    const prompt = agentInput;
    setAgentInput('');

    try {
        const result = await applyAgenticEdit(files, prompt, project);
        onFilesUpdate(result.updatedFiles);
        setChatHistory(prev => [...prev, { role: 'ai', text: "I've updated the code based on your request." }]);
    } catch (e) {
        setChatHistory(prev => [...prev, { role: 'ai', text: "Error applying changes." }]);
    } finally {
        setIsThinking(false);
    }
  };

  const currentFileContent = files.find(f => f.name === activeFile)?.content || '';

  return (
    <div className="flex h-[calc(100vh-140px)] w-full bg-[#050507] text-slate-300 font-sans border border-slate-800/60 rounded-xl overflow-hidden shadow-2xl relative group">
      {/* Glossy Overlay */}
      <div className="absolute inset-0 bg-gradient-to-br from-indigo-500/5 via-transparent to-cyan-500/5 pointer-events-none z-10"></div>
      
      {/* Sidebar */}
      <div className={`${isSidebarOpen ? 'w-72' : 'w-0'} bg-slate-900/80 backdrop-blur-md border-r border-slate-800 transition-all duration-300 flex flex-col overflow-hidden relative z-20`}>
        <div className="p-4 border-b border-slate-800 flex items-center justify-between">
            <span className="font-bold text-xs uppercase tracking-wider text-slate-400">Explorer</span>
            <FolderOpen size={14} className="text-slate-600" />
        </div>
        
        <div className="flex-1 overflow-y-auto py-2">
            {files.map(file => (
                <div 
                    key={file.name}
                    onClick={() => setActiveFile(file.name)}
                    className={`flex items-center px-4 py-2.5 cursor-pointer text-sm hover:bg-white/5 transition-all border-l-2 ${activeFile === file.name ? 'bg-cyan-500/10 text-cyan-400 border-cyan-500' : 'text-slate-400 border-transparent opacity-80 hover:opacity-100'}`}
                >
                    {getFileIcon(file.name, file.language)}
                    <span className="truncate font-mono text-xs">{file.name}</span>
                </div>
            ))}
        </div>
        
        {/* Quick Chat */}
        <div className="border-t border-slate-800 bg-[#0a0a0c]">
            <div className="p-3 border-b border-slate-800 flex items-center justify-between bg-gradient-to-r from-purple-900/20 to-transparent">
                <div className="flex items-center text-xs font-bold text-purple-400">
                    <Sparkles size={12} className="mr-2" /> AI Copilot
                </div>
            </div>
            
            <div className="h-40 overflow-y-auto p-3 text-[11px] space-y-3 scrollbar-hide">
                {chatHistory.length === 0 && (
                    <div className="text-center text-slate-600 mt-4 italic">
                        Ask me to modify colors, fix bugs, or add features...
                    </div>
                )}
                {chatHistory.map((msg, i) => (
                    <div key={i} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
                        <div className={`max-w-[85%] p-2 rounded-lg ${msg.role === 'user' ? 'bg-purple-500/20 text-purple-200 border border-purple-500/30' : 'bg-slate-800 text-slate-300 border border-slate-700'}`}>
                           {msg.text}
                        </div>
                    </div>
                ))}
                {isThinking && (
                    <div className="flex items-center space-x-1 text-slate-500 pl-1">
                        <span className="w-1 h-1 bg-slate-500 rounded-full animate-bounce"></span>
                        <span className="w-1 h-1 bg-slate-500 rounded-full animate-bounce delay-100"></span>
                        <span className="w-1 h-1 bg-slate-500 rounded-full animate-bounce delay-200"></span>
                    </div>
                )}
                <div ref={chatEndRef} />
            </div>
            
            <div className="p-2 relative">
                <input 
                    className="w-full bg-slate-800/50 border border-slate-700 rounded-lg p-2.5 pr-8 text-xs focus:border-purple-500 focus:bg-slate-800 outline-none transition-all placeholder-slate-600 text-slate-300"
                    placeholder="Refactor this code..."
                    value={agentInput}
                    onChange={e => setAgentInput(e.target.value)}
                    onKeyDown={e => e.key === 'Enter' && handleAgentSubmit()}
                />
                <button onClick={handleAgentSubmit} className="absolute right-4 top-4 text-purple-500 hover:text-white transition-colors">
                    <Send size={12} />
                </button>
            </div>
        </div>
      </div>

      {/* Editor */}
      <div className="flex-1 flex flex-col bg-[#050507] relative z-20">
         <div className="h-10 bg-slate-900/50 border-b border-slate-800 flex items-center px-4 justify-between backdrop-blur-sm">
            <div className="flex items-center">
                <button onClick={() => setIsSidebarOpen(!isSidebarOpen)} className="mr-4 text-slate-500 hover:text-white transition-colors"><Menu size={16} /></button>
                <FileCode size={14} className="mr-2 text-cyan-500" />
                <span className="text-xs font-mono text-slate-300">{activeFile}</span>
            </div>
            <div className="flex items-center space-x-3 text-[10px] text-slate-500">
                <span className="flex items-center"><span className="w-1.5 h-1.5 rounded-full bg-green-500 mr-1.5"></span> Live</span>
                <span>UTF-8</span>
            </div>
         </div>
         <div className="flex-1 relative">
            <textarea
                value={currentFileContent}
                onChange={(e) => handleCodeChange(e.target.value)}
                className="absolute inset-0 w-full h-full bg-[#050507] text-slate-300 font-mono p-6 resize-none outline-none border-none leading-relaxed text-sm selection:bg-purple-500/30"
                spellCheck={false}
            />
         </div>
      </div>
    </div>
  );
};
